[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
amiquip = { version = "0.4", default-features = false }
regex = "1.7.1"
prost = "0.11.8"
rayon = "1.7.0"
serde_json = "1.0.94"
serde = "1.0.152"
