name: Queue CI (Elixir)

on:
  push:
    branches: ["main"]
    paths: ["apps/queue/**"]
  pull_request:
    branches: ["main"]
    paths: ["apps/queue/**"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: apps/queue

env:
  ImageOS: "ubuntu20"
  MIX_ENV: "test"
  OTP_VERSION_SPEC: "25.2"
  ELIXIR_VERSION_SPEC: "1.14.3"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
          version-type: "strict"
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Prepare protoc
        run: sudo apt install -y protobuf-compiler && git clone https://fuchsia.googlesource.com/third_party/googleapis ./tmp && mv ./tmp/* ../prototype
      - name: Install protoc-gen-elixir
        run: mix escript.install hex protobuf --force
      - name: Install dependencies
        run: mix deps.get
      - name: Compile Protos
        run: mix proto.compile
      - name: Run tests
        run: mix test
