name: Web CI (Astro)

on:
  push:
    branches: ["main"]
    paths: ["apps/web/**"]
  pull_request:
    branches: ["main"]
    paths: ["apps/web/**"]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 19.2.0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: pnpm build

      # - name: Install Playwright Browsers
      #   run: pnpm dlx playwright install --with-deps

      # - name: Run Playwright tests
      #   run: pnpm dlx playwright test

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: apps/web/playwright-report/
      #     retention-days: 30
